# Generated by Django 3.2.6 on 2021-08-04 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='titulo',
            new_name='tituloo',
        ),
    ]
