# Generated by Django 3.2.6 on 2021-09-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0002_auto_20210913_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='marca',
            field=models.CharField(choices=[('ACURA', 'ACURA'), ('AGRALE', 'AGRALE'), ('ALFA ROMEO', 'ALFA ROMEO'), ('ASIA MOTOR', 'ASIA'), ('ASTON MARTIN', 'ASTON'), ('AUDI', 'AUDI'), ('BMW', 'BMW'), ('BRANDY', 'BRANDY'), ('CAGIVA', 'CAGIVA'), ('CALOI', 'CALOI'), ('CAOA CHERY', 'CAOA CHERY'), ('CITROEN', 'CITROEN'), ('CHANGAN', 'CHANGAN'), ('CHRYSLER', 'CHRYSLER'), ('CROSS LANDER', 'CROSS LANDER'), ('DAELIM', 'DAELIM'), ('DAEWOO', 'DAEWOO'), ('DAFRA', 'DAFRA'), ('DAIHATSU', 'DAIHATSU'), ('DODGE', 'DODGE'), ('DUCATI', 'DUCATI'), ('EFFA', 'EFFA'), ('ENGESA', 'ENGESA'), ('FERRARI', 'FERRARI'), ('FIAT', 'FIAT'), ('FORD', 'FORD'), ('FOX', 'FOX'), ('FYM', 'FYM'), ('GM-CHEVROLET', 'GM-CHEVROLET'), ('GURGEL', 'GURGEL'), ('HAFEI', 'HAFEI'), ('HARLEY-DAVIDSON', 'HARLEY-DAVIDSON'), ('HARTFORD', 'HARTFORD'), ('HERO', 'HERO'), ('HITECH ELETRIC', 'HITECH ELETRIC'), ('HONDA', 'HONDA'), ('HUSABERG', 'HUSABERG'), ('INDIAN', 'INDIAN'), ('IROS', 'IROS'), ('IVECO', 'IVECO'), ('JAC', 'JAC'), ('JAGUAR', 'JAGUAR'), ('JEEP', 'JEEP'), ('KASINKI', 'KASINKI'), ('KAWAKASI', 'KAWAKASI'), ('KIA MOTORS', 'KIA MOTORS'), ('LADA', 'LADA'), ('LAMBORGHINI', 'LAMBORGHINI'), ('LAND ROVER', 'LAND ROVER'), ('LEXUS', 'LEXUS'), ('LIFAN', 'LIFAN'), ('MAHINDRA', 'MAHINDRA'), ('MALAGUTI', 'MALAGUTI'), ('MATRA', 'MATRA'), ('MAZDA', 'MAZDA'), ('MERCEDEZ-BENZ', 'MERCEDEZ-BENZ'), ('MERCURY', 'MERCURY'), ('MG', 'MG'), ('MINI', 'MINI'), ('MITA', 'MITA'), ('MITSUBISHI', 'MITSUBISHI'), ('MOTOCAR', 'MOTOCAR'), ('MVK', 'MVK'), ('PEGEOUT', 'PEGEOUT'), ('PONTIAC', 'PONTIAC'), ('PORSHE', 'PORSHE'), ('RAM', 'RAM'), ('RENAULT', 'RENAULT'), ('ROLLS-ROYCE', 'ROLLS-ROYCE'), ('SHINERAY', 'SHINERAY'), ('SIAMOTO', 'SIAMOTO'), ('SUNDOWN', 'SUNDOWN'), ('SUZUKI', 'SUZUKI'), ('TAC', 'TAC'), ('TARGOS', 'TARGOS'), ('TIGER', 'TIGER'), ('VOLCANO', 'VOLCANO'), ('YAMAHA', 'YAMAHA')], max_length=20),
        ),
    ]
