# Generated by Django 3.2.6 on 2021-09-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0003_alter_anuncio_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='combustível',
            field=models.CharField(choices=[('GASOLINA', 'GASOLINA'), ('ALCOOL', 'ALCOOL'), ('FLEX', 'FLEX'), ('DIESEL', 'DIESEL'), ('GNV', 'GNV'), ('MIX (ALCOOL/GASOLINA', 'MIX (ALCOOL/GASOLINA')], max_length=20),
        ),
    ]
