# Generated by Django 3.2.6 on 2021-08-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0004_alter_anuncio_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagem',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
