# Generated by Django 3.2.6 on 2021-09-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0004_alter_anuncio_combustível'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='valor',
            field=models.CharField(max_length=9),
        ),
    ]
