# Generated by Django 3.2.6 on 2021-09-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0005_alter_anuncio_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='imagem',
        ),
    ]
