# Generated by Django 3.2.6 on 2021-09-10 04:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0006_remove_anuncio_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='imagem',
            field=django_resized.forms.ResizedImageField(crop=None, default=0, force_format=None, keep_meta=True, quality=0, size=[500, 300], upload_to='media/'),
            preserve_default=False,
        ),
    ]
