# Generated by Django 3.2.6 on 2021-09-10 05:33

from django.db import migrations
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0008_auto_20210910_0147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnuncioPhoto',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
