# Generated by Django 3.2.6 on 2021-09-21 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0009_auto_20210916_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='combustível',
            new_name='combustivel',
        ),
    ]
