# Generated by Django 3.2.6 on 2021-09-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0009_auto_20210910_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='image',
        ),
    ]
