# Generated by Django 3.2.6 on 2021-09-21 22:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0010_rename_combustível_anuncio_combustivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.IntegerField(max_length=11)),
                ('NOME', models.CharField(max_length=50)),
                ('ENDEREÇO', models.CharField(max_length=50)),
                ('NUMERO', models.CharField(max_length=4)),
                ('BAIRRO', models.CharField(max_length=25)),
                ('CEP', models.IntegerField(max_length=9)),
                ('NOME_ANUNCIANTE', models.CharField(max_length=15)),
                ('WHATSAPP', phonenumber_field.modelfields.PhoneNumberField(max_length=11, region=None, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='combustivel',
            new_name='combustível',
        ),
    ]
