# Generated by Django 3.2.6 on 2021-09-10 16:13

from django.db import migrations
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0010_remove_anuncio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='imagem',
            field=django_resized.forms.ResizedImageField(crop=None, default=django.utils.timezone.now, force_format=None, keep_meta=True, quality=0, size=[1920, 1080], upload_to='media/'),
            preserve_default=False,
        ),
    ]
