# Generated by Django 3.2.6 on 2021-09-22 01:18

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0011_auto_20210921_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='CEP',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='particular',
            name='CPF',
            field=django_cpf_cnpj.fields.CPFField(max_length=14),
        ),
    ]
