# Generated by Django 3.2.7 on 2021-09-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0012_auto_20210921_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Particular',
        ),
    ]
