# Generated by Django 3.2.7 on 2021-10-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0013_delete_particular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
